### ISSUE TITLE
tsd demands to have index.d.ts where it is not required

### ISSUE THREAD

**Issue by StreetStrider** [SamVerschueren/tsd#84] opened 2020-10-30 17:39 UTC
Consider we have package with single module `foo.js` and definitions in `foo.d.ts`. We got `"main": "foo.js"`.
If we run tsd on such package, we got:
```
The type definition `index.d.ts` does not exist. Create one and try again.
```
However, this file is redundant at such case.

**Comment by yss14** [comment] 2020-11-27 10:41
Even with a `tsd.directory` property set in `package.json` this error comes up.

**Comment by seancroach** [comment] 2020-12-31 06:04
Any progress on this?

Roughly eight months ago I remember having to deal with this rather annoying bug; now I'm having to use this package again and it seems the way I previously got around this does not work.

As of now, `tsd` is simply unusable in what I'd consider being a realistic configuration due to this false negative throwing an error.

**Comment by UselessPickles** [comment] 2021-02-13 17:20
@StreetStrider Does your `package.json` specify `"types": "foo.d.ts"`?

My understanding is that `tsd` looks for the type definitions file specified by `package.json`, but defaults to looking for `index.d.ts`.

**Comment by StreetStrider** [comment] 2021-02-13 23:15
@UselessPickles that is not exactly my case. package.json `types` means we're intending to export types. I'm not exporting anything in that particular case. I just have JS module and corresponding d.ts and no index.js at all. If tsd follows TS semantics this should work (because tsc can compile such setup and I have proper tsconfig.json), however it isn't and it points to the redundant nonexistent file. :thinking:

**Comment by UselessPickles** [comment] 2021-02-13 23:23
@StreetStrider Sounds like this might be a duplicate of (or similar to) #32.

See my comment for a workaround: https://github.com/SamVerschueren/tsd/issues/32#issuecomment-778650556

**Comment by StreetStrider** [comment] 2021-02-13 23:33
@UselessPickles thanks. That's indeed looks similar. I ended up using dtslint, but it also has its issues (and it is more complex). I solve them similar to your workaround, by creating test subproject with it's own tsconfig which satisfies all limitations. Both systems are not ideal for me and have issues. My use-case is to have expect-typish like tests in my project. I believe, TS projects must have type tests just like they have unit-tests. Having positive and negative type tests is the only way to guarantee your types are correct and that they can be consumed by library user.

**Comment by BendingBender** [comment] 2021-05-24 17:29
@SamVerschueren I've tested it out, it seems that it suffices to have a `.d.ts` file that has the same name as the `main` entrypoint in `package.json`, an explicit `types` field is not required for TypeScript to pick up the definitions. I.e. if the `main` entrypoint to a package is `foo.js` then it suffices to have a `foo.d.ts` for the typings to work correctly.

Do you mind if I implement this logic or do you insist on having an explicit `types` field in the `package.json`?

**Comment by BendingBender** [comment] 2021-05-28 21:47
@sindresorhus Not sure whether I should start implementing it because I don't know whether this is intended behavior or not. @SamVerschueren  doesn't answer, do you have an opinion on this?

**Comment by SamVerschueren** [comment] 2021-05-28 21:51
@BendingBender feel free to pick it up! Didn't knew that a typings field was not necessary. Seems like a good one to have 👍.

**Closed** 2021-06-01 08:16 UTC
