### ISSUE TITLE
tsd throws errors inside node_modules

### ISSUE THREAD

**Issue by jLouzado** [SamVerschueren/tsd#76] opened 2020-08-27 21:32 UTC
## Problem

- I've setup a test in the root of my project folder
- the test passes as expected, but then it fails because of errors thrown from node_modules

```
➜  data-aware git:(develop) ✗ yarn tsd
yarn run v1.12.1
$ /Users/joel/Projects/data-aware/node_modules/.bin/tsd

  node_modules/@types/react-highcharts/index.d.ts:22:32
  ✖  22:32  Namespace "/Users/<user>/Projects/data-aware/node_modules/highcharts/highcharts" has no exported member ChartObject.  
  ✖  34:34  Namespace "/Users/<user>/Projects/data-aware/node_modules/highcharts/highcharts" has no exported member Static.       

  2 errors

error Command failed with exit code 1.
```

I tried specifically excluding node_modules by specifying tsconfig from within package.json but to no avail.

## TSConfig

```json
{
  "compilerOptions": {
    "declaration": false,
    "module": "commonjs",
    "newLine": "LF",
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es6",
    "skipLibCheck": true
  },
  "exclude": ["node_modules"]
}
```

**Comment by edi9999** [comment] 2020-09-03 08:35
I have the same issue, I also don't want to check anything inside my node_modules.

**Comment by edi9999** [comment] 2020-09-03 08:42
In my case, I had : 

````
  node_modules/@types/puppeteer/index.d.ts:26:45
  ✖   26:45  Cannot find name Element.
  ✖   62:28  Cannot find name Element.
  ✖   78:28  Cannot find name Element.
  ✖   96:28  Cannot find name Element.
  ✖  116:28  Cannot find name Element.
  ✖  135:28  Cannot find name Element.
  ✖  151:29  Cannot find name Element.
  ✖  167:29  Cannot find name Element.
  ✖  185:29  Cannot find name Element.
  ✖  205:29  Cannot find name Element.
  ✖  224:29  Cannot find name Element.
  ✖  768:41  Cannot find name Element.
  ✖  768:51  Cannot find name Element.
```

So adding the following to my package.json fixed the issue : 


```
  "tsd": {
    "compilerOptions": {
      "lib": [
        "DOM"
      ]
    }
  }
```

However, this works only because the errors that are shown in my case are DOM related (Element exists only in DOM).

**Comment by fregante** [comment] 2020-10-09 17:35
Duplicate of https://github.com/SamVerschueren/tsd/issues/45

**Comment by BendingBender** [comment] 2021-05-29 17:20
@jLouzado @edi9999 

Would you mind testing my branch (https://github.com/BendingBender/tsd/tree/ignore-errors-from-node-modules) and reporting whether it fixes the problem for you? Thanks!

**Closed** 2021-06-01 08:13 UTC
